name: Checks
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Checks
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: |
          pip install --upgrade pip
          pip install black flake8 mypy==v0.902 isort autoflake
          isort --recursive  --force-single-line-imports
          autoflake --in-place --remove-unused-variables --remove-all-unused-imports --expand-star-imports
          black --diff --check app
          flake8
          mypy --disallow-untyped-defs --disallow-untyped-calls --check-untyped-defs app
